import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { link } from "fs";
import Email from "@/app/components/icons/social/Email";
import LinkedIn from "@/app/components/icons/social/LinkedIn";
import GitHub from "@/app/components/icons/social/GitHub";
import React from "react";
import Link from "next/link";
import Navbar from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const social = [
  {
    title: "GitHub",
    icon: <GitHub />,
    link: ""
  },
  {
    title: "LinkedIn",
    icon: <LinkedIn />,
    link: ""
  },
  {
    title: "Email",
    icon: <Email />,
    link: ""
  },
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-black flex items-center justify-center h-screen"}>
        <div className="mr-5 p-3 flex flex-col justify-between items-center w-[184px] h-[611px] bg-default">
          <div className="flex justify-between w-[80%] mt-3">
            {social.map(({ icon, link, title }) => {
              return (
                <a key={title} href={link} target="_blank">
                  {React.cloneElement(icon, { className: "fill-secondary h-[20px] w-[20px]" })}
                </a>
              )
            })}
          </div>
          <Navbar />
          <p className="text-xs">João Pereira, All Rights Reserved</p>
        </div>
        <div className="bg-default w-[532px] h-[611px]">
          {children}
        </div>
      </body>
    </html>
  );
}
