import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Email from "@/app/components/icons/social/emai";
import React from "react";
import Navbar from "./components/navbar";
import LinkedIn from "./components/icons/social/linkedin";
import GitHub from "./components/icons/social/github";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const social = [
  {
    title: "GitHub",
    Icon: GitHub,
    link: ""
  },
  {
    title: "LinkedIn",
    Icon: LinkedIn,
    link: ""
  },
  {
    title: "Email",
    Icon: Email,
    link: ""
  },
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-black flex items-center justify-center h-screen"}>
        <div className="mr-5 p-3 flex flex-col justify-between items-center w-[194px] h-[611px] bg-default">
          <div className="flex justify-between w-[80%] mt-3">
            {social.map(({ Icon, link, title }) => {
              return (
                <a key={title} href={link} target="_blank">
                  <Icon className="fill-secondary h-[20px] w-[20px]" />
                </a>
              )
            })}
          </div>
          <Navbar />
          <p className="text-xs">João Pereira, All Rights Reserved</p>
        </div>
        <div className="bg-default w-[667px] h-[611px]">
          {children}
        </div>
      </body>
    </html>
  );
}
